let employeesData = [
  {
    id: 1,
    name: "Ben",
    role: "Analyst",
    location: "Vareš",
    active: false,
  },
  {
    id: 2,
    name: "Waly",
    role: "Analyst",
    location: "Khasht’arrak",
    active: true,
  },
  {
    id: 3,
    name: "Debby",
    role: "Doctor",
    location: "Ciparay",
    active: false,
  },
  {
    id: 4,
    name: "Elysee",
    role: "Backend Developer",
    location: "Piggs Peak",
    active: false,
  },
  {
    id: 5,
    name: "Mirabel",
    role: "Teacher",
    location: "Pulau Pinang",
    active: true,
  },
  {
    id: 6,
    name: "Rogers",
    role: "HR",
    location: "Mel’nikovo",
    active: true,
  },
  {
    id: 7,
    name: "Kyle",
    role: "Doctor",
    location: "Rantepang",
    active: false,
  },
  {
    id: 8,
    name: "Rebecka",
    role: "Frontend Developer",
    location: "Maoyang",
    active: true,
  },
  {
    id: 9,
    name: "Emeline",
    role: "Developer",
    location: "Täby",
    active: true,
  },
  {
    id: 10,
    name: "Windham",
    role: "HR",
    location: "Bulupayung",
    active: true,
  },
  {
    id: 11,
    name: "Lauryn",
    role: "Frontend Developer",
    location: "Drumcondra",
    active: false,
  },
  {
    id: 12,
    name: "Larina",
    role: "Backend Developer",
    location: "Maykopskoye",
    active: false,
  },
  {
    id: 13,
    name: "Fredia",
    role: "HR",
    location: "San Nicolas",
    active: true,
  },
  {
    id: 14,
    name: "Reta",
    role: "Doctor",
    location: "Sarzedo",
    active: true,
  },
  {
    id: 15,
    name: "Claresta",
    role: "Freelancer",
    location: "Cantoria",
    active: false,
  },
  {
    id: 16,
    name: "Bartholemy",
    role: "Doctor",
    location: "Nizhniy Ufaley",
    active: false,
  },
  {
    id: 17,
    name: "Vida",
    role: "Doctor",
    location: "Nice",
    active: false,
  },
  {
    id: 18,
    name: "Cello",
    role: "Teacher",
    location: "Zarechnyy",
    active: false,
  },
  {
    id: 19,
    name: "Tammi",
    role: "HR",
    location: "Takasaki",
    active: false,
  },
  {
    id: 20,
    name: "Buffy",
    role: "Teacher",
    location: "Fonte de Angeão",
    active: true,
  },
  {
    id: 21,
    name: "Ede",
    role: "HR",
    location: "Magole",
    active: true,
  },
  {
    id: 22,
    name: "Winfred",
    role: "Doctor",
    location: "Toktogul",
    active: false,
  },
  {
    id: 23,
    name: "Egan",
    role: "Teacher",
    location: "Dayong",
    active: false,
  },
  {
    id: 24,
    name: "Ryann",
    role: "HR",
    location: "Józefów",
    active: true,
  },
  {
    id: 25,
    name: "Hayes",
    role: "Analyst",
    location: "Yuta",
    active: false,
  },
  {
    id: 26,
    name: "Delaney",
    role: "Analyst",
    location: "Maragogipe",
    active: true,
  },
  {
    id: 27,
    name: "Avis",
    role: "HR",
    location: "Songshu",
    active: true,
  },
  {
    id: 28,
    name: "Biron",
    role: "Student",
    location: "Xiaoshan",
    active: false,
  },
  {
    id: 29,
    name: "Baillie",
    role: "Analyst",
    location: "Jagupit",
    active: true,
  },
  {
    id: 30,
    name: "Wally",
    role: "Teacher",
    location: "Stockholm",
    active: true,
  },
  {
    id: 31,
    name: "Krissy",
    role: "Backend Developer",
    location: "Lublin",
    active: true,
  },
  {
    id: 32,
    name: "Lyndel",
    role: "Developer",
    location: "Negla",
    active: false,
  },
  {
    id: 33,
    name: "Jarvis",
    role: "Analyst",
    location: "Pentaplátano",
    active: false,
  },
  {
    id: 34,
    name: "Myrah",
    role: "Analyst",
    location: "Erqu",
    active: true,
  },
  {
    id: 35,
    name: "Jennie",
    role: "Student",
    location: "Sindanghayu",
    active: false,
  },
  {
    id: 36,
    name: "Torrance",
    role: "HR",
    location: "Wufeng",
    active: false,
  },
  {
    id: 37,
    name: "Lyda",
    role: "Student",
    location: "Tayum",
    active: false,
  },
  {
    id: 38,
    name: "Astrix",
    role: "Freelancer",
    location: "Roi Et",
    active: true,
  },
  {
    id: 39,
    name: "Collin",
    role: "Backend Developer",
    location: "Pushkino",
    active: false,
  },
  {
    id: 40,
    name: "Emyle",
    role: "Teacher",
    location: "Dongobesh",
    active: false,
  },
  {
    id: 41,
    name: "Noach",
    role: "Freelancer",
    location: "Kaédi",
    active: true,
  },
  {
    id: 42,
    name: "Polly",
    role: "Developer",
    location: "Tucurú",
    active: false,
  },
  {
    id: 43,
    name: "Arlena",
    role: "Developer",
    location: "Dve Mogili",
    active: false,
  },
  {
    id: 44,
    name: "Clarette",
    role: "Analyst",
    location: "Jiyukou",
    active: false,
  },
  {
    id: 45,
    name: "Jone",
    role: "Frontend Developer",
    location: "Yuanling",
    active: true,
  },
  {
    id: 46,
    name: "Stephi",
    role: "Developer",
    location: "Maogang",
    active: true,
  },
  {
    id: 47,
    name: "Murray",
    role: "Analyst",
    location: "Pedamaran",
    active: false,
  },
  {
    id: 48,
    name: "Bekki",
    role: "Backend Developer",
    location: "Mezhdurechensk",
    active: false,
  },
  {
    id: 49,
    name: "Stefanie",
    role: "Backend Developer",
    location: "Horad Smalyavichy",
    active: false,
  },
  {
    id: 50,
    name: "Julina",
    role: "Doctor",
    location: "Gorna Oryakhovitsa",
    active: true,
  },
];

module.exports = employeesData;
